/*
 * Adobe Experience Manager (AEM) API
 * Swagger AEM is an OpenAPI specification for Adobe Experience Manager (AEM) API
 *
 * The version of the OpenAPI document: 3.7.1-pre.0
 * Contact: opensource@shinesolutions.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package client.model.adobe;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.Assert;

import org.junit.Test;
import org.openapitools.client.model.adobe.SamlConfigurationPropertyItemsBoolean;

/**
 * Model tests for SamlConfigurationPropertyItemsBoolean
 */
public class SamlConfigurationPropertyItemsBooleanTest {
    private final SamlConfigurationPropertyItemsBoolean model = new SamlConfigurationPropertyItemsBoolean();

    /**
     * Model tests for SamlConfigurationPropertyItemsBoolean
     */
    @Test
    public void testSamlConfigurationPropertyItemsBoolean() {
        // TODO: test SamlConfigurationPropertyItemsBoolean
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'isSet'
     */
    @Test
    public void isSetTest() {
        // TODO: test isSet
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'optional'
     */
    @Test
    public void optionalTest() {
        // TODO: test optional
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
