/*
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.6
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package client.model.petStoreModel;

import base.CustomLoggingFilter;
import io.qameta.allure.Epic;
import io.qameta.allure.Feature;
import io.qameta.allure.Story;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.response.Response;
import io.restassured.response.ValidatableResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import org.openapitools.client.api.petStoreApi.PetApi;
import org.openapitools.client.model.petStoreModel.Pet;

import org.openapitools.client.service.petStoreService.ApiClient;

import static io.qameta.allure.Allure.step;
import static io.restassured.config.ObjectMapperConfig.objectMapperConfig;
import static io.restassured.config.RestAssuredConfig.config;
import static org.hamcrest.CoreMatchers.containsString;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.openapitools.client.service.petStoreService.GsonObjectMapper.gson;

/**
 * Model tests for Pet
 */
@Tag("base")
@Epic("setEpic")
@Feature("setFeature")
@Story("setStory")
//@Disabled
public class PetTest {
    private final Pet model = new Pet();
    private PetApi api;

    @BeforeEach
    public void createApi() {
        api = ApiClient.api(ApiClient.Config.apiConfig().reqSpecSupplier(
                () -> new RequestSpecBuilder()
                        .setConfig(config().objectMapperConfig(objectMapperConfig().defaultObjectMapper(gson())))
//                        .addFilter(new ErrorLoggingFilter())
                        .addFilter(new CustomLoggingFilter())
                        .setBaseUri("https://petstore.swagger.io/v2"))).pet();
    }

    /**
     * Model tests for Pet
     */
    @EnumSource(PetModelPositiveCase.class)
    @ParameterizedTest(name = "{0}")
    @DisplayName("param test pet")
    public void testPet(PetModelPositiveCase testCase) {
        Response response = step("act: Create a new pet in the store", () -> {
            // Adjusted API call to match the builder pattern
            return api.addPet()
                    .body(testCase.getPet())
                    .execute(r -> r.prettyPeek());
        });
        step("asssert: Create a new pet in the store", () -> {
            // Assert that the response status code is as expected
            assertEquals(testCase.getStatusCode(), response.getStatusCode(), "Status code does not match the expected value.");
        });
    }

    @EnumSource(PetModelPositiveCase.class)
    @ParameterizedTest(name = "{0}")
    @DisplayName("param test pet")
    public void testPetV2(PetModelPositiveCase testCase) {
        ValidatableResponse response = step("act: Create a new pet in the store", () -> {
            // Adjusted API call to use ValidatableResponse
            return api.addPet()
                    .body(testCase.getPet())
                    .execute(r -> r.prettyPeek())
                    .then()
                    .statusCode(testCase.getStatusCode());
        });

        step("asssert: Create a new pet in the store", () -> {
            // Assert that the response status code is as expected
            assertEquals(testCase.getStatusCode(), response.extract().statusCode(), "Status code does not match the expected value.");
            // 2th way to assert status code
            response
                    .assertThat()
                    .body( "name", containsString("doggie"));
        });

    }


    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'photoUrls'
     */
    @Test
    public void photoUrlsTest() {
        // TODO: test photoUrls
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
