/*
 * Adobe Experience Manager (AEM) API
 * Swagger AEM is an OpenAPI specification for Adobe Experience Manager (AEM) API
 *
 * The version of the OpenAPI document: 3.7.1-pre.0
 * Contact: opensource@shinesolutions.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.generator.adobe;

import base.BaseAdobeApiTest;
import io.qameta.allure.Epic;
import io.qameta.allure.Feature;
import io.qameta.allure.Story;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.openapitools.client.api.adobe.CqApi;

@Tag("base")
@Epic("setEpic")
@Feature("setFeature")
@Story("setStory")
@Disabled
public class CqApiTest extends BaseTest {

    private CqApi api = cqApi;


    /**
     * Default response
     */
    @Test
    public void shouldSee0AfterGetLoginPage() {
        api.getLoginPage().execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * Default response
     */
    @Test
    public void shouldSee0AfterPostCqActions() {
        String authorizableId = null;
        String changelog = null;
        api.postCqActions()
                .authorizableIdQuery(authorizableId)
                .changelogQuery(changelog).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

}
